name: Node.js CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: npm install -g corepack@latest
      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"
      - run: |
        pnpm i
        pnpm run test

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g corepack@latest
      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"
      - run: |
        pnpm i
        pnpm run build
